sudo: true
language: ruby
install: true
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      rvm: 2.6
      env:
        - BUILD_ENGINE=native
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=ubuntu-1404
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=ubuntu-1604
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=debian-7
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=debian-8
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=centos-6
      services:
        - docker
    - os: linux
      env:
        - BUILD_ENGINE=docker
        - DOCKER_TAG=centos-7
      services:
        - docker
before_install:
  - buildscripts/travis-pre-build.sh
script:
  - rm -f pkg/*
  - "buildscripts/${BUILD_ENGINE}.sh"
  - mkdir -p "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/"
  - sudo chown -R "$USER" pkg
  - mv pkg "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/pkg"
  - ls -lah "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/pkg"
deploy:
  skip_cleanup: true
  provider: s3
  bucket: omnibus-aptible-toolbelt
  acl: public_read
  local_dir: deploy
  access_key_id:
    secure: "rnPMjsmXroxgf7nJkaIb164j8vWflCP7kMmLF8vcFp2h8L3dPDrv0eqd3B2EP5ajCdLT/xwyFDEnlS3JIubSNeBF9S64DOzLK20SLu7ZVE5oYBxrM1zvPSIGH45rEq//i++Cqj5HBTkPsS+UHEuncrpxjAmxdPfi7+IIEZOL6SLb9IztCFtF/5rYC6rz05oE++QcZDI23SUAV0Ru02gKaYSkQbnNCtBhJ1cZspXEIiThQLaBj72lD3RdHEBXlTUGd5ydq74y20dS8WPnDNvaRWvyYnLeWUoDvu7ZcXw4kkQds0fmDQCo6cEm4Qikm8GT8TKDizCRRP8+pwm1JzCeS0K09WcteMCiOPshL43lz9NDLI/jz3EgEKGAAt9sfarLfjNFdU1VkDksYSEq04UUiO39ED9vuZKDNtra4MJ+PE2AEnbCb7WqA0NlA2zjqp+exqXswVQvlc313oHftkTIycjOS4ba0gnzykWU4ATIkkyIJCPAgUg8DwJIwgXllSIWgbeNJPNALs3gZ+9PUzoKqjL62CdhOKW8p9Vf2cpgZr60w3WPNAAPzsFuL5wKceldrLuoW0Q7KTM+nEMZMITFCSqEXwZ6mJenYhm03iLojoLKezo/jusS/ZSsP976pHkdq041bGCIRuKnbnKT5bNVFzRd76zL6nR6WNnJhK5BJIQ="
  secret_access_key:
    secure: "M3PE6irxs2vm++i146LcGboX/Z+O/c5ticL6vcO2vPp9VQZZcNgsIVBybZVRrJFA08kCxwzi9YLEi2ehCTpEDmjSjy1pSfNAR6M9UxnMmmgzpSZP0I7IHlBHkTmqULQi7yEPM4eA8D7dTVqhAsx/5LDjFMlaZFUddlVAPNPur/VphXHvqTZeI20WCIYLPF88F4oofILO5P7aKIP3inTgoK096vhxv4mDkiPCL6QDI+GdYE0HIVtV8v0+ZqYk1niEqiY7g6S5xPeC2fRclfJe7bDRPegahq0uJVZ9xYy/ZFyRbiKJyXcT5rYrxOaocSXsHVAedK/fLq70cGL3xwHq4XCysYj7HS0ywUda7odobNzMWC0KErfoLblZ8nFDNv9ApZ5TOym3KepvndEFxAw3ouR10mdd9P51/HNnx7y8xdvEPWgzThv5NiNOt6/T4Wb24mQI7VpvpoSsC2pY7WjhnE66vbhtI6q/C1zPLdskChFnO+Vev80QzBCphAplv1+9FCrwSm40kqm23p5nyO4ONTJY8EvQH4prvKL+ig0stryBH5qsY5wvUZI/dNF2HiJ9G2Wox4z9iN4gO7jMnYI2Ok13cuT+1Zg0ciB4nWuKEVuqrffS+K5xB3ewaoEZLX4esfovdDfhRo13sVVHhp/gmtw3lvA5YLEHTBjfvuSYErI="
  on:
    repo: aptible/omnibus-aptible-toolbelt
    all_branches: true
